definitions:
  books.AddBookRequestBody:
    properties:
      author:
        type: string
      description:
        type: string
      title:
        type: string
    type: object
  models.BookResponse:
    properties:
      author:
        type: string
      description:
        type: string
      title:
        type: string
    type: object
  models.UpdateBookRequestBody:
    properties:
      author:
        type: string
      description:
        type: string
      title:
        type: string
    type: object
  models.UserResponse:
    properties:
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
  users.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  users.SignUpUserRequest:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Testing Swagger APIs.
  termsOfService: http://swagger.io/terms/
  title: BookStore APIs
  version: "1.0"
paths:
  /:
    get:
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /api/admin/user:
    get:
      description: Get token from users cookee
      operationId: get-current-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
      summary: get current user
      tags:
      - Authentication
  /books:
    get:
      description: Get all books from db
      operationId: get-all-books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BookResponse'
            type: array
      summary: get all books
      tags:
      - Books
    post:
      consumes:
      - application/json
      description: Creating Book in DB with given request body
      parameters:
      - description: Введите данные статьи
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/books.AddBookRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - JWT: []
      summary: create new Book
      tags:
      - Books
  /books/{id}:
    delete:
      description: Delete a book by ID
      operationId: delete-book-by-id
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: delete a book by ID
      tags:
      - Books
    get:
      description: Get an book by ID
      operationId: get-book-by-id
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookResponse'
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: get an book by ID
      tags:
      - Books
    put:
      description: Update book by ID
      operationId: delete-book-by-id
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Введите новые данные книги
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateBookRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: update book by ID
      tags:
      - Books
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticate User in app with given request body
      parameters:
      - description: Введите данные для авторизации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.LoginInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: user authentication
      tags:
      - Authentication
  /users/logout:
    get:
      description: Clear JWT token by setting an empty value and expired time in the
        cookie
      operationId: logout-current-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: logout current user
      tags:
      - Authentication
  /users/register:
    post:
      consumes:
      - application/json
      description: Register User in app with given request body
      parameters:
      - description: Введите данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.SignUpUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: user registration
      tags:
      - Authentication
securityDefinitions:
  JWT:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
